
#include <cassert>
#include <format>
#include <string>
#include <iostream>
#include <array>


using std::format;
using std::cout;

int main()
{

    cout << "# Negative\n";

    cout << "## Align: Default\n";
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);
    cout << format("{{:8x}}         -  |{:8x}|\n", -42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", -42);
    cout << format("{{:08x}}        -  |{:08x}|\n", -42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", -42);

    cout << "## Align: Left\n";
    cout << format("{{:<8x}}        -  |{:<8x}|\n", -42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", -42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", -42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", -42);
    cout << format("{{:<8x}}        -  |{:<8x}|\n", -42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", -42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", -42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", -42);
    cout << format("{{:<8x}}        -  |{:<8x}|\n", -42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", -42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", -42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", -42);
    cout << format("{{:<8x}}        -  |{:<8x}|\n", -42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", -42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", -42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", -42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", -42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", -42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", -42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", -42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", -42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", -42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", -42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", -42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", -42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", -42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", -42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", -42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", -42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", -42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", -42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", -42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", -42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", -42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", -42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", -42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", -42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", -42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", -42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", -42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", -42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", -42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", -42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", -42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", -42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", -42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", -42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", -42);

    cout << "## Align: Right\n";
    cout << format("{{:>8x}}        -  |{:>8x}|\n", -42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", -42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", -42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", -42);
    cout << format("{{:>8x}}        -  |{:>8x}|\n", -42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", -42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", -42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", -42);
    cout << format("{{:>8x}}        -  |{:>8x}|\n", -42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", -42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", -42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", -42);
    cout << format("{{:>8x}}        -  |{:>8x}|\n", -42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", -42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", -42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", -42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", -42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", -42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", -42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", -42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", -42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", -42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", -42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", -42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", -42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", -42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", -42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", -42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", -42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", -42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", -42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", -42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", -42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", -42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", -42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", -42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", -42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", -42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", -42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", -42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", -42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", -42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", -42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", -42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", -42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", -42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", -42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", -42);

    cout << "## Align: Center\n";
    cout << format("{{:^8x}}        -  |{:^8x}|\n", -42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", -42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", -42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", -42);
    cout << format("{{:^8x}}        -  |{:^8x}|\n", -42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", -42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", -42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", -42);
    cout << format("{{:^8x}}        -  |{:^8x}|\n", -42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", -42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", -42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", -42);
    cout << format("{{:^8x}}        -  |{:^8x}|\n", -42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", -42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", -42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", -42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", -42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", -42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", -42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", -42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", -42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", -42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", -42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", -42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", -42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", -42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", -42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", -42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", -42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", -42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", -42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", -42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", -42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", -42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", -42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", -42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", -42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", -42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", -42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", -42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", -42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", -42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", -42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", -42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", -42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", -42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", -42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", -42);

    cout << "# Positive\n";

    cout << "## Align: Default\n";
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);
    cout << format("{{:8x}}         -  |{:8x}|\n", 42);
    cout << format("{{:#8x}}        -  |{:#8x}|\n", 42);
    cout << format("{{:08x}}        -  |{:08x}|\n", 42);
    cout << format("{{:#08x}}       -  |{:#08x}|\n", 42);

    cout << "## Align: Left\n";
    cout << format("{{:<8x}}        -  |{:<8x}|\n", 42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", 42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", 42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", 42);
    cout << format("{{:<8x}}        -  |{:<8x}|\n", 42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", 42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", 42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", 42);
    cout << format("{{:<8x}}        -  |{:<8x}|\n", 42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", 42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", 42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", 42);
    cout << format("{{:<8x}}        -  |{:<8x}|\n", 42);
    cout << format("{{:<#8x}}       -  |{:<#8x}|\n", 42);
    cout << format("{{:<08x}}       -  |{:<08x}|\n", 42);
    cout << format("{{:<#08x}}      -  |{:<#08x}|\n", 42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", 42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", 42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", 42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", 42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", 42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", 42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", 42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", 42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", 42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", 42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", 42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", 42);
    cout << format("{{: <8x}}       -  |{: <8x}|\n", 42);
    cout << format("{{: <#8x}}      -  |{: <#8x}|\n", 42);
    cout << format("{{: <08x}}      -  |{: <08x}|\n", 42);
    cout << format("{{: <#08x}}     -  |{: <#08x}|\n", 42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", 42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", 42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", 42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", 42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", 42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", 42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", 42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", 42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", 42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", 42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", 42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", 42);
    cout << format("{{:*<8x}}       -  |{:*<8x}|\n", 42);
    cout << format("{{:*<#8x}}      -  |{:*<#8x}|\n", 42);
    cout << format("{{:*<08x}}      -  |{:*<08x}|\n", 42);
    cout << format("{{:*<#08x}}     -  |{:*<#08x}|\n", 42);

    cout << "## Align: Right\n";
    cout << format("{{:>8x}}        -  |{:>8x}|\n", 42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", 42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", 42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", 42);
    cout << format("{{:>8x}}        -  |{:>8x}|\n", 42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", 42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", 42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", 42);
    cout << format("{{:>8x}}        -  |{:>8x}|\n", 42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", 42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", 42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", 42);
    cout << format("{{:>8x}}        -  |{:>8x}|\n", 42);
    cout << format("{{:>#8x}}       -  |{:>#8x}|\n", 42);
    cout << format("{{:>08x}}       -  |{:>08x}|\n", 42);
    cout << format("{{:>#08x}}      -  |{:>#08x}|\n", 42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", 42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", 42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", 42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", 42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", 42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", 42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", 42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", 42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", 42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", 42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", 42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", 42);
    cout << format("{{: >8x}}       -  |{: >8x}|\n", 42);
    cout << format("{{: >#8x}}      -  |{: >#8x}|\n", 42);
    cout << format("{{: >08x}}      -  |{: >08x}|\n", 42);
    cout << format("{{: >#08x}}     -  |{: >#08x}|\n", 42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", 42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", 42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", 42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", 42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", 42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", 42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", 42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", 42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", 42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", 42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", 42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", 42);
    cout << format("{{:*>8x}}       -  |{:*>8x}|\n", 42);
    cout << format("{{:*>#8x}}      -  |{:*>#8x}|\n", 42);
    cout << format("{{:*>08x}}      -  |{:*>08x}|\n", 42);
    cout << format("{{:*>#08x}}     -  |{:*>#08x}|\n", 42);

    cout << "## Align: Center\n";
    cout << format("{{:^8x}}        -  |{:^8x}|\n", 42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", 42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", 42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", 42);
    cout << format("{{:^8x}}        -  |{:^8x}|\n", 42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", 42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", 42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", 42);
    cout << format("{{:^8x}}        -  |{:^8x}|\n", 42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", 42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", 42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", 42);
    cout << format("{{:^8x}}        -  |{:^8x}|\n", 42);
    cout << format("{{:^#8x}}       -  |{:^#8x}|\n", 42);
    cout << format("{{:^08x}}       -  |{:^08x}|\n", 42);
    cout << format("{{:^#08x}}      -  |{:^#08x}|\n", 42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", 42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", 42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", 42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", 42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", 42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", 42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", 42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", 42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", 42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", 42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", 42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", 42);
    cout << format("{{: ^8x}}       -  |{: ^8x}|\n", 42);
    cout << format("{{: ^#8x}}      -  |{: ^#8x}|\n", 42);
    cout << format("{{: ^08x}}      -  |{: ^08x}|\n", 42);
    cout << format("{{: ^#08x}}     -  |{: ^#08x}|\n", 42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", 42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", 42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", 42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", 42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", 42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", 42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", 42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", 42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", 42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", 42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", 42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", 42);
    cout << format("{{:*^8x}}       -  |{:*^8x}|\n", 42);
    cout << format("{{:*^#8x}}      -  |{:*^#8x}|\n", 42);
    cout << format("{{:*^08x}}      -  |{:*^08x}|\n", 42);
    cout << format("{{:*^#08x}}     -  |{:*^#08x}|\n", 42);

}

