
#include <cassert>
#include <string>
#include <iostream>
#include <array>


#include "marty_format/marty_format.h"


using std::cout;
using namespace marty::format;

int main()
{
    cout << formatMessage("{{:0}}          -  |{:0}|\n", {-420} );
    cout << formatMessage("{{:0b}}         -  |{:0b}|\n", {-420} );
    cout << formatMessage("{{:0x}}         -  |{:0x}|\n", {-420} );
    cout << formatMessage("{{:0X}}         -  |{:0X}|\n", {-420} );
    cout << formatMessage("{{:0%}}         -  |{:0%}|\n", {-420} );
    cout << formatMessage("{{:0'b}}        -  |{:0'b}|\n", {-420} );
    cout << formatMessage("{{:0'x}}        -  |{:0'x}|\n", {-420} );
    cout << formatMessage("{{:0'X}}        -  |{:0'X}|\n", {-420} );
    cout << formatMessage("{{:12}}         -  |{:12}|\n", {-420} );
    cout << formatMessage("{{:12b}}        -  |{:12b}|\n", {-420} );
    cout << formatMessage("{{:12x}}        -  |{:12x}|\n", {-420} );
    cout << formatMessage("{{:12X}}        -  |{:12X}|\n", {-420} );
    cout << formatMessage("{{:12%}}        -  |{:12%}|\n", {-420} );
    cout << formatMessage("{{:12'b}}       -  |{:12'b}|\n", {-420} );
    cout << formatMessage("{{:#0b}}        -  |{:#0b}|\n", {-420} );
    cout << formatMessage("{{:#0x}}        -  |{:#0x}|\n", {-420} );
    cout << formatMessage("{{:#0X}}        -  |{:#0X}|\n", {-420} );
    cout << formatMessage("{{:#0h}}        -  |{:#0h}|\n", {-420} );
    cout << formatMessage("{{:#0'b}}       -  |{:#0'b}|\n", {-420} );
    cout << formatMessage("{{:#0'x}}       -  |{:#0'x}|\n", {-420} );
    cout << formatMessage("{{:#0'X}}       -  |{:#0'X}|\n", {-420} );
    cout << formatMessage("{{:#0'h}}       -  |{:#0'h}|\n", {-420} );
    cout << formatMessage("{{:#12b}}       -  |{:#12b}|\n", {-420} );
    cout << formatMessage("{{:#12x}}       -  |{:#12x}|\n", {-420} );
    cout << formatMessage("{{:#12X}}       -  |{:#12X}|\n", {-420} );
    cout << formatMessage("{{:#12h}}       -  |{:#12h}|\n", {-420} );
    cout << formatMessage("{{:#12'b}}      -  |{:#12'b}|\n", {-420} );
    cout << formatMessage("{{:012}}        -  |{:012}|\n", {-420} );
    cout << formatMessage("{{:012b}}       -  |{:012b}|\n", {-420} );
    cout << formatMessage("{{:012x}}       -  |{:012x}|\n", {-420} );
    cout << formatMessage("{{:012X}}       -  |{:012X}|\n", {-420} );
    cout << formatMessage("{{:012%}}       -  |{:012%}|\n", {-420} );
    cout << formatMessage("{{:012'}}       -  |{:012'}|\n", {-420} );
    cout << formatMessage("{{:012'x}}      -  |{:012'x}|\n", {-420} );
    cout << formatMessage("{{:012'X}}      -  |{:012'X}|\n", {-420} );
    cout << formatMessage("{{:012'%}}      -  |{:012'%}|\n", {-420} );
    cout << formatMessage("{{:#012x}}      -  |{:#012x}|\n", {-420} );
    cout << formatMessage("{{:#012X}}      -  |{:#012X}|\n", {-420} );
    cout << formatMessage("{{:#012h}}      -  |{:#012h}|\n", {-420} );
    cout << formatMessage("{{:#012'h}}     -  |{:#012'h}|\n", {-420} );
    cout << formatMessage("{{:!#0b}}       -  |{:!#0b}|\n", {-420} );
    cout << formatMessage("{{:!#0x}}       -  |{:!#0x}|\n", {-420} );
    cout << formatMessage("{{:!#0X}}       -  |{:!#0X}|\n", {-420} );
    cout << formatMessage("{{:!#0h}}       -  |{:!#0h}|\n", {-420} );
    cout << formatMessage("{{:!#0'b}}      -  |{:!#0'b}|\n", {-420} );
    cout << formatMessage("{{:!#0'x}}      -  |{:!#0'x}|\n", {-420} );
    cout << formatMessage("{{:!#0'X}}      -  |{:!#0'X}|\n", {-420} );
    cout << formatMessage("{{:!#0'h}}      -  |{:!#0'h}|\n", {-420} );
    cout << formatMessage("{{:!#12b}}      -  |{:!#12b}|\n", {-420} );
    cout << formatMessage("{{:!#12x}}      -  |{:!#12x}|\n", {-420} );
    cout << formatMessage("{{:!#12X}}      -  |{:!#12X}|\n", {-420} );
    cout << formatMessage("{{:!#12h}}      -  |{:!#12h}|\n", {-420} );
    cout << formatMessage("{{:!#12'b}}     -  |{:!#12'b}|\n", {-420} );
    cout << formatMessage("{{:!#012x}}     -  |{:!#012x}|\n", {-420} );
    cout << formatMessage("{{:!#012X}}     -  |{:!#012X}|\n", {-420} );
    cout << formatMessage("{{:!#012h}}     -  |{:!#012h}|\n", {-420} );
    cout << formatMessage("{{:!#012'h}}    -  |{:!#012'h}|\n", {-420} );
    cout << formatMessage("{{:~0b}}        -  |{:~0b}|\n", {-420} );
    cout << formatMessage("{{:~0x}}        -  |{:~0x}|\n", {-420} );
    cout << formatMessage("{{:~0X}}        -  |{:~0X}|\n", {-420} );
    cout << formatMessage("{{:~0'b}}       -  |{:~0'b}|\n", {-420} );
    cout << formatMessage("{{:~0'x}}       -  |{:~0'x}|\n", {-420} );
    cout << formatMessage("{{:~0'X}}       -  |{:~0'X}|\n", {-420} );
    cout << formatMessage("{{:~12x}}       -  |{:~12x}|\n", {-420} );
    cout << formatMessage("{{:~12X}}       -  |{:~12X}|\n", {-420} );
    cout << formatMessage("{{:~12'x}}      -  |{:~12'x}|\n", {-420} );
    cout << formatMessage("{{:~12'X}}      -  |{:~12'X}|\n", {-420} );
    cout << formatMessage("{{:~#0b}}       -  |{:~#0b}|\n", {-420} );
    cout << formatMessage("{{:~#0x}}       -  |{:~#0x}|\n", {-420} );
    cout << formatMessage("{{:~#0X}}       -  |{:~#0X}|\n", {-420} );
    cout << formatMessage("{{:~#0h}}       -  |{:~#0h}|\n", {-420} );
    cout << formatMessage("{{:~#0'b}}      -  |{:~#0'b}|\n", {-420} );
    cout << formatMessage("{{:~#0'x}}      -  |{:~#0'x}|\n", {-420} );
    cout << formatMessage("{{:~#0'X}}      -  |{:~#0'X}|\n", {-420} );
    cout << formatMessage("{{:~#0'h}}      -  |{:~#0'h}|\n", {-420} );
    cout << formatMessage("{{:~#12x}}      -  |{:~#12x}|\n", {-420} );
    cout << formatMessage("{{:~#12X}}      -  |{:~#12X}|\n", {-420} );
    cout << formatMessage("{{:~#12h}}      -  |{:~#12h}|\n", {-420} );
    cout << formatMessage("{{:~#12'x}}     -  |{:~#12'x}|\n", {-420} );
    cout << formatMessage("{{:~#12'X}}     -  |{:~#12'X}|\n", {-420} );
    cout << formatMessage("{{:~#12'h}}     -  |{:~#12'h}|\n", {-420} );
    cout << formatMessage("{{:~012x}}      -  |{:~012x}|\n", {-420} );
    cout << formatMessage("{{:~012X}}      -  |{:~012X}|\n", {-420} );
    cout << formatMessage("{{:~012'x}}     -  |{:~012'x}|\n", {-420} );
    cout << formatMessage("{{:~012'X}}     -  |{:~012'X}|\n", {-420} );
    cout << formatMessage("{{:~#012x}}     -  |{:~#012x}|\n", {-420} );
    cout << formatMessage("{{:~#012X}}     -  |{:~#012X}|\n", {-420} );
    cout << formatMessage("{{:~#012h}}     -  |{:~#012h}|\n", {-420} );
    cout << formatMessage("{{:~#012'x}}    -  |{:~#012'x}|\n", {-420} );
    cout << formatMessage("{{:~#012'X}}    -  |{:~#012'X}|\n", {-420} );
    cout << formatMessage("{{:~#012'h}}    -  |{:~#012'h}|\n", {-420} );
    cout << formatMessage("{{:~!#0b}}      -  |{:~!#0b}|\n", {-420} );
    cout << formatMessage("{{:~!#0x}}      -  |{:~!#0x}|\n", {-420} );
    cout << formatMessage("{{:~!#0X}}      -  |{:~!#0X}|\n", {-420} );
    cout << formatMessage("{{:~!#0h}}      -  |{:~!#0h}|\n", {-420} );
    cout << formatMessage("{{:~!#0'b}}     -  |{:~!#0'b}|\n", {-420} );
    cout << formatMessage("{{:~!#0'x}}     -  |{:~!#0'x}|\n", {-420} );
    cout << formatMessage("{{:~!#0'X}}     -  |{:~!#0'X}|\n", {-420} );
    cout << formatMessage("{{:~!#0'h}}     -  |{:~!#0'h}|\n", {-420} );
    cout << formatMessage("{{:~!#12x}}     -  |{:~!#12x}|\n", {-420} );
    cout << formatMessage("{{:~!#12X}}     -  |{:~!#12X}|\n", {-420} );
    cout << formatMessage("{{:~!#12h}}     -  |{:~!#12h}|\n", {-420} );
    cout << formatMessage("{{:~!#12'x}}    -  |{:~!#12'x}|\n", {-420} );
    cout << formatMessage("{{:~!#12'X}}    -  |{:~!#12'X}|\n", {-420} );
    cout << formatMessage("{{:~!#12'h}}    -  |{:~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:~!#012x}}    -  |{:~!#012x}|\n", {-420} );
    cout << formatMessage("{{:~!#012X}}    -  |{:~!#012X}|\n", {-420} );
    cout << formatMessage("{{:~!#012h}}    -  |{:~!#012h}|\n", {-420} );
    cout << formatMessage("{{:~!#012'x}}   -  |{:~!#012'x}|\n", {-420} );
    cout << formatMessage("{{:~!#012'X}}   -  |{:~!#012'X}|\n", {-420} );
    cout << formatMessage("{{:~!#012'h}}   -  |{:~!#012'h}|\n", {-420} );
    cout << formatMessage("{{:+~0b}}       -  |{:+~0b}|\n", {-420} );
    cout << formatMessage("{{:+~0x}}       -  |{:+~0x}|\n", {-420} );
    cout << formatMessage("{{:+~0X}}       -  |{:+~0X}|\n", {-420} );
    cout << formatMessage("{{:+~0'b}}      -  |{:+~0'b}|\n", {-420} );
    cout << formatMessage("{{:+~0'x}}      -  |{:+~0'x}|\n", {-420} );
    cout << formatMessage("{{:+~0'X}}      -  |{:+~0'X}|\n", {-420} );
    cout << formatMessage("{{:+~12x}}      -  |{:+~12x}|\n", {-420} );
    cout << formatMessage("{{:+~12X}}      -  |{:+~12X}|\n", {-420} );
    cout << formatMessage("{{:+~12'x}}     -  |{:+~12'x}|\n", {-420} );
    cout << formatMessage("{{:+~12'X}}     -  |{:+~12'X}|\n", {-420} );
    cout << formatMessage("{{:+~#0b}}      -  |{:+~#0b}|\n", {-420} );
    cout << formatMessage("{{:+~#0x}}      -  |{:+~#0x}|\n", {-420} );
    cout << formatMessage("{{:+~#0X}}      -  |{:+~#0X}|\n", {-420} );
    cout << formatMessage("{{:+~#0h}}      -  |{:+~#0h}|\n", {-420} );
    cout << formatMessage("{{:+~#0'b}}     -  |{:+~#0'b}|\n", {-420} );
    cout << formatMessage("{{:+~#0'x}}     -  |{:+~#0'x}|\n", {-420} );
    cout << formatMessage("{{:+~#0'X}}     -  |{:+~#0'X}|\n", {-420} );
    cout << formatMessage("{{:+~#0'h}}     -  |{:+~#0'h}|\n", {-420} );
    cout << formatMessage("{{:+~#12x}}     -  |{:+~#12x}|\n", {-420} );
    cout << formatMessage("{{:+~#12X}}     -  |{:+~#12X}|\n", {-420} );
    cout << formatMessage("{{:+~#12h}}     -  |{:+~#12h}|\n", {-420} );
    cout << formatMessage("{{:+~#12'h}}    -  |{:+~#12'h}|\n", {-420} );
    cout << formatMessage("{{:+~012x}}     -  |{:+~012x}|\n", {-420} );
    cout << formatMessage("{{:+~012X}}     -  |{:+~012X}|\n", {-420} );
    cout << formatMessage("{{:+~012'x}}    -  |{:+~012'x}|\n", {-420} );
    cout << formatMessage("{{:+~012'X}}    -  |{:+~012'X}|\n", {-420} );
    cout << formatMessage("{{:+~#012x}}    -  |{:+~#012x}|\n", {-420} );
    cout << formatMessage("{{:+~#012X}}    -  |{:+~#012X}|\n", {-420} );
    cout << formatMessage("{{:+~#012h}}    -  |{:+~#012h}|\n", {-420} );
    cout << formatMessage("{{:+~#012'h}}   -  |{:+~#012'h}|\n", {-420} );
    cout << formatMessage("{{:+~!#0b}}     -  |{:+~!#0b}|\n", {-420} );
    cout << formatMessage("{{:+~!#0x}}     -  |{:+~!#0x}|\n", {-420} );
    cout << formatMessage("{{:+~!#0X}}     -  |{:+~!#0X}|\n", {-420} );
    cout << formatMessage("{{:+~!#0h}}     -  |{:+~!#0h}|\n", {-420} );
    cout << formatMessage("{{:+~!#0'b}}    -  |{:+~!#0'b}|\n", {-420} );
    cout << formatMessage("{{:+~!#0'x}}    -  |{:+~!#0'x}|\n", {-420} );
    cout << formatMessage("{{:+~!#0'X}}    -  |{:+~!#0'X}|\n", {-420} );
    cout << formatMessage("{{:+~!#0'h}}    -  |{:+~!#0'h}|\n", {-420} );
    cout << formatMessage("{{:+~!#12x}}    -  |{:+~!#12x}|\n", {-420} );
    cout << formatMessage("{{:+~!#12X}}    -  |{:+~!#12X}|\n", {-420} );
    cout << formatMessage("{{:+~!#12h}}    -  |{:+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:+~!#12'h}}   -  |{:+~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:+~!#012x}}   -  |{:+~!#012x}|\n", {-420} );
    cout << formatMessage("{{:+~!#012X}}   -  |{:+~!#012X}|\n", {-420} );
    cout << formatMessage("{{:+~!#012h}}   -  |{:+~!#012h}|\n", {-420} );
    cout << formatMessage("{{:+~!#012'h}}  -  |{:+~!#012'h}|\n", {-420} );
    cout << formatMessage("{{:=12}}        -  |{:=12}|\n", {-420} );
    cout << formatMessage("{{:=12b}}       -  |{:=12b}|\n", {-420} );
    cout << formatMessage("{{:=12x}}       -  |{:=12x}|\n", {-420} );
    cout << formatMessage("{{:=12X}}       -  |{:=12X}|\n", {-420} );
    cout << formatMessage("{{:=12%}}       -  |{:=12%}|\n", {-420} );
    cout << formatMessage("{{:=#12x}}      -  |{:=#12x}|\n", {-420} );
    cout << formatMessage("{{:=#12X}}      -  |{:=#12X}|\n", {-420} );
    cout << formatMessage("{{:=#12h}}      -  |{:=#12h}|\n", {-420} );
    cout << formatMessage("{{:=!#12x}}     -  |{:=!#12x}|\n", {-420} );
    cout << formatMessage("{{:=!#12X}}     -  |{:=!#12X}|\n", {-420} );
    cout << formatMessage("{{:=!#12h}}     -  |{:=!#12h}|\n", {-420} );
    cout << formatMessage("{{:=~12x}}      -  |{:=~12x}|\n", {-420} );
    cout << formatMessage("{{:=~12X}}      -  |{:=~12X}|\n", {-420} );
    cout << formatMessage("{{:=~12'x}}     -  |{:=~12'x}|\n", {-420} );
    cout << formatMessage("{{:=~12'X}}     -  |{:=~12'X}|\n", {-420} );
    cout << formatMessage("{{:=~#12x}}     -  |{:=~#12x}|\n", {-420} );
    cout << formatMessage("{{:=~#12X}}     -  |{:=~#12X}|\n", {-420} );
    cout << formatMessage("{{:=~#12h}}     -  |{:=~#12h}|\n", {-420} );
    cout << formatMessage("{{:=~#12'x}}    -  |{:=~#12'x}|\n", {-420} );
    cout << formatMessage("{{:=~#12'X}}    -  |{:=~#12'X}|\n", {-420} );
    cout << formatMessage("{{:=~#12'h}}    -  |{:=~#12'h}|\n", {-420} );
    cout << formatMessage("{{:=~!#12x}}    -  |{:=~!#12x}|\n", {-420} );
    cout << formatMessage("{{:=~!#12X}}    -  |{:=~!#12X}|\n", {-420} );
    cout << formatMessage("{{:=~!#12h}}    -  |{:=~!#12h}|\n", {-420} );
    cout << formatMessage("{{:=~!#12'x}}   -  |{:=~!#12'x}|\n", {-420} );
    cout << formatMessage("{{:=~!#12'X}}   -  |{:=~!#12'X}|\n", {-420} );
    cout << formatMessage("{{:=~!#12'h}}   -  |{:=~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:=+~12x}}     -  |{:=+~12x}|\n", {-420} );
    cout << formatMessage("{{:=+~12X}}     -  |{:=+~12X}|\n", {-420} );
    cout << formatMessage("{{:=+~12'x}}    -  |{:=+~12'x}|\n", {-420} );
    cout << formatMessage("{{:=+~12'X}}    -  |{:=+~12'X}|\n", {-420} );
    cout << formatMessage("{{:=+~#12x}}    -  |{:=+~#12x}|\n", {-420} );
    cout << formatMessage("{{:=+~#12X}}    -  |{:=+~#12X}|\n", {-420} );
    cout << formatMessage("{{:=+~#12h}}    -  |{:=+~#12h}|\n", {-420} );
    cout << formatMessage("{{:=+~#12'h}}   -  |{:=+~#12'h}|\n", {-420} );
    cout << formatMessage("{{:=+~!#12x}}   -  |{:=+~!#12x}|\n", {-420} );
    cout << formatMessage("{{:=+~!#12X}}   -  |{:=+~!#12X}|\n", {-420} );
    cout << formatMessage("{{:=+~!#12h}}   -  |{:=+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:=+~!#12'h}}  -  |{:=+~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:= ~0b}}      -  |{:= ~0b}|\n", {-420} );
    cout << formatMessage("{{:= ~0x}}      -  |{:= ~0x}|\n", {-420} );
    cout << formatMessage("{{:= ~0X}}      -  |{:= ~0X}|\n", {-420} );
    cout << formatMessage("{{:= ~0'b}}     -  |{:= ~0'b}|\n", {-420} );
    cout << formatMessage("{{:= ~0'x}}     -  |{:= ~0'x}|\n", {-420} );
    cout << formatMessage("{{:= ~0'X}}     -  |{:= ~0'X}|\n", {-420} );
    cout << formatMessage("{{:= ~#0b}}     -  |{:= ~#0b}|\n", {-420} );
    cout << formatMessage("{{:= ~#0x}}     -  |{:= ~#0x}|\n", {-420} );
    cout << formatMessage("{{:= ~#0X}}     -  |{:= ~#0X}|\n", {-420} );
    cout << formatMessage("{{:= ~#0h}}     -  |{:= ~#0h}|\n", {-420} );
    cout << formatMessage("{{:= ~#0'b}}    -  |{:= ~#0'b}|\n", {-420} );
    cout << formatMessage("{{:= ~#0'h}}    -  |{:= ~#0'h}|\n", {-420} );
    cout << formatMessage("{{:= ~012x}}    -  |{:= ~012x}|\n", {-420} );
    cout << formatMessage("{{:= ~012X}}    -  |{:= ~012X}|\n", {-420} );
    cout << formatMessage("{{:= ~012'x}}   -  |{:= ~012'x}|\n", {-420} );
    cout << formatMessage("{{:= ~012'X}}   -  |{:= ~012'X}|\n", {-420} );
    cout << formatMessage("{{:= ~#012x}}   -  |{:= ~#012x}|\n", {-420} );
    cout << formatMessage("{{:= ~#012X}}   -  |{:= ~#012X}|\n", {-420} );
    cout << formatMessage("{{:= ~#012h}}   -  |{:= ~#012h}|\n", {-420} );
    cout << formatMessage("{{:= ~#012'h}}  -  |{:= ~#012'h}|\n", {-420} );
    cout << formatMessage("{{:= ~!#0b}}    -  |{:= ~!#0b}|\n", {-420} );
    cout << formatMessage("{{:= ~!#0x}}    -  |{:= ~!#0x}|\n", {-420} );
    cout << formatMessage("{{:= ~!#0X}}    -  |{:= ~!#0X}|\n", {-420} );
    cout << formatMessage("{{:= ~!#0h}}    -  |{:= ~!#0h}|\n", {-420} );
    cout << formatMessage("{{:= ~!#0'b}}   -  |{:= ~!#0'b}|\n", {-420} );
    cout << formatMessage("{{:= ~!#0'h}}   -  |{:= ~!#0'h}|\n", {-420} );
    cout << formatMessage("{{:= ~!#012x}}  -  |{:= ~!#012x}|\n", {-420} );
    cout << formatMessage("{{:= ~!#012X}}  -  |{:= ~!#012X}|\n", {-420} );
    cout << formatMessage("{{:= ~!#012h}}  -  |{:= ~!#012h}|\n", {-420} );
    cout << formatMessage("{{:= ~!#012'h}}  -  |{:= ~!#012'h}|\n", {-420} );
    cout << formatMessage("{{:*=12}}       -  |{:*=12}|\n", {-420} );
    cout << formatMessage("{{:*=12b}}      -  |{:*=12b}|\n", {-420} );
    cout << formatMessage("{{:*=12x}}      -  |{:*=12x}|\n", {-420} );
    cout << formatMessage("{{:*=12X}}      -  |{:*=12X}|\n", {-420} );
    cout << formatMessage("{{:*=12%}}      -  |{:*=12%}|\n", {-420} );
    cout << formatMessage("{{:*=#12x}}     -  |{:*=#12x}|\n", {-420} );
    cout << formatMessage("{{:*=#12X}}     -  |{:*=#12X}|\n", {-420} );
    cout << formatMessage("{{:*=#12h}}     -  |{:*=#12h}|\n", {-420} );
    cout << formatMessage("{{:*=!#12x}}    -  |{:*=!#12x}|\n", {-420} );
    cout << formatMessage("{{:*=!#12X}}    -  |{:*=!#12X}|\n", {-420} );
    cout << formatMessage("{{:*=!#12h}}    -  |{:*=!#12h}|\n", {-420} );
    cout << formatMessage("{{:*=~12x}}     -  |{:*=~12x}|\n", {-420} );
    cout << formatMessage("{{:*=~12X}}     -  |{:*=~12X}|\n", {-420} );
    cout << formatMessage("{{:*=~12'x}}    -  |{:*=~12'x}|\n", {-420} );
    cout << formatMessage("{{:*=~12'X}}    -  |{:*=~12'X}|\n", {-420} );
    cout << formatMessage("{{:*=~#12x}}    -  |{:*=~#12x}|\n", {-420} );
    cout << formatMessage("{{:*=~#12X}}    -  |{:*=~#12X}|\n", {-420} );
    cout << formatMessage("{{:*=~#12h}}    -  |{:*=~#12h}|\n", {-420} );
    cout << formatMessage("{{:*=~#12'x}}   -  |{:*=~#12'x}|\n", {-420} );
    cout << formatMessage("{{:*=~#12'X}}   -  |{:*=~#12'X}|\n", {-420} );
    cout << formatMessage("{{:*=~#12'h}}   -  |{:*=~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*=~!#12x}}   -  |{:*=~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*=~!#12X}}   -  |{:*=~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*=~!#12h}}   -  |{:*=~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*=~!#12'x}}  -  |{:*=~!#12'x}|\n", {-420} );
    cout << formatMessage("{{:*=~!#12'X}}  -  |{:*=~!#12'X}|\n", {-420} );
    cout << formatMessage("{{:*=~!#12'h}}  -  |{:*=~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*=+~12x}}    -  |{:*=+~12x}|\n", {-420} );
    cout << formatMessage("{{:*=+~12X}}    -  |{:*=+~12X}|\n", {-420} );
    cout << formatMessage("{{:*=+~12'x}}   -  |{:*=+~12'x}|\n", {-420} );
    cout << formatMessage("{{:*=+~12'X}}   -  |{:*=+~12'X}|\n", {-420} );
    cout << formatMessage("{{:*=+~#12x}}   -  |{:*=+~#12x}|\n", {-420} );
    cout << formatMessage("{{:*=+~#12X}}   -  |{:*=+~#12X}|\n", {-420} );
    cout << formatMessage("{{:*=+~#12h}}   -  |{:*=+~#12h}|\n", {-420} );
    cout << formatMessage("{{:*=+~#12'h}}  -  |{:*=+~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*=+~!#12x}}  -  |{:*=+~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*=+~!#12X}}  -  |{:*=+~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*=+~!#12h}}  -  |{:*=+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*=+~!#12'h}}  -  |{:*=+~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*= ~12x}}    -  |{:*= ~12x}|\n", {-420} );
    cout << formatMessage("{{:*= ~12X}}    -  |{:*= ~12X}|\n", {-420} );
    cout << formatMessage("{{:*= ~12'x}}   -  |{:*= ~12'x}|\n", {-420} );
    cout << formatMessage("{{:*= ~12'X}}   -  |{:*= ~12'X}|\n", {-420} );
    cout << formatMessage("{{:*= ~#12x}}   -  |{:*= ~#12x}|\n", {-420} );
    cout << formatMessage("{{:*= ~#12X}}   -  |{:*= ~#12X}|\n", {-420} );
    cout << formatMessage("{{:*= ~#12h}}   -  |{:*= ~#12h}|\n", {-420} );
    cout << formatMessage("{{:*= ~#12'h}}  -  |{:*= ~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*= ~!#12x}}  -  |{:*= ~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*= ~!#12X}}  -  |{:*= ~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*= ~!#12h}}  -  |{:*= ~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*= ~!#12'h}}  -  |{:*= ~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:<0b}}        -  |{:<0b}|\n", {-420} );
    cout << formatMessage("{{:<0x}}        -  |{:<0x}|\n", {-420} );
    cout << formatMessage("{{:<0X}}        -  |{:<0X}|\n", {-420} );
    cout << formatMessage("{{:<#0x}}       -  |{:<#0x}|\n", {-420} );
    cout << formatMessage("{{:<#0X}}       -  |{:<#0X}|\n", {-420} );
    cout << formatMessage("{{:<#0h}}       -  |{:<#0h}|\n", {-420} );
    cout << formatMessage("{{:<!#0x}}      -  |{:<!#0x}|\n", {-420} );
    cout << formatMessage("{{:<!#0X}}      -  |{:<!#0X}|\n", {-420} );
    cout << formatMessage("{{:<!#0h}}      -  |{:<!#0h}|\n", {-420} );
    cout << formatMessage("{{:< ~12x}}     -  |{:< ~12x}|\n", {-420} );
    cout << formatMessage("{{:< ~12X}}     -  |{:< ~12X}|\n", {-420} );
    cout << formatMessage("{{:< ~12'x}}    -  |{:< ~12'x}|\n", {-420} );
    cout << formatMessage("{{:< ~12'X}}    -  |{:< ~12'X}|\n", {-420} );
    cout << formatMessage("{{:< ~#12x}}    -  |{:< ~#12x}|\n", {-420} );
    cout << formatMessage("{{:< ~#12X}}    -  |{:< ~#12X}|\n", {-420} );
    cout << formatMessage("{{:< ~#12h}}    -  |{:< ~#12h}|\n", {-420} );
    cout << formatMessage("{{:< ~#12'h}}   -  |{:< ~#12'h}|\n", {-420} );
    cout << formatMessage("{{:< ~!#12x}}   -  |{:< ~!#12x}|\n", {-420} );
    cout << formatMessage("{{:< ~!#12X}}   -  |{:< ~!#12X}|\n", {-420} );
    cout << formatMessage("{{:< ~!#12h}}   -  |{:< ~!#12h}|\n", {-420} );
    cout << formatMessage("{{:< ~!#12'h}}  -  |{:< ~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*<12}}       -  |{:*<12}|\n", {-420} );
    cout << formatMessage("{{:*<12b}}      -  |{:*<12b}|\n", {-420} );
    cout << formatMessage("{{:*<12x}}      -  |{:*<12x}|\n", {-420} );
    cout << formatMessage("{{:*<12X}}      -  |{:*<12X}|\n", {-420} );
    cout << formatMessage("{{:*<12%}}      -  |{:*<12%}|\n", {-420} );
    cout << formatMessage("{{:*<#12x}}     -  |{:*<#12x}|\n", {-420} );
    cout << formatMessage("{{:*<#12X}}     -  |{:*<#12X}|\n", {-420} );
    cout << formatMessage("{{:*<#12h}}     -  |{:*<#12h}|\n", {-420} );
    cout << formatMessage("{{:*<!#12x}}    -  |{:*<!#12x}|\n", {-420} );
    cout << formatMessage("{{:*<!#12X}}    -  |{:*<!#12X}|\n", {-420} );
    cout << formatMessage("{{:*<!#12h}}    -  |{:*<!#12h}|\n", {-420} );
    cout << formatMessage("{{:*<~12x}}     -  |{:*<~12x}|\n", {-420} );
    cout << formatMessage("{{:*<~12X}}     -  |{:*<~12X}|\n", {-420} );
    cout << formatMessage("{{:*<~12'x}}    -  |{:*<~12'x}|\n", {-420} );
    cout << formatMessage("{{:*<~12'X}}    -  |{:*<~12'X}|\n", {-420} );
    cout << formatMessage("{{:*<~#12x}}    -  |{:*<~#12x}|\n", {-420} );
    cout << formatMessage("{{:*<~#12X}}    -  |{:*<~#12X}|\n", {-420} );
    cout << formatMessage("{{:*<~#12h}}    -  |{:*<~#12h}|\n", {-420} );
    cout << formatMessage("{{:*<~#12'x}}   -  |{:*<~#12'x}|\n", {-420} );
    cout << formatMessage("{{:*<~#12'X}}   -  |{:*<~#12'X}|\n", {-420} );
    cout << formatMessage("{{:*<~#12'h}}   -  |{:*<~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*<~!#12x}}   -  |{:*<~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*<~!#12X}}   -  |{:*<~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*<~!#12h}}   -  |{:*<~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*<~!#12'x}}  -  |{:*<~!#12'x}|\n", {-420} );
    cout << formatMessage("{{:*<~!#12'X}}  -  |{:*<~!#12'X}|\n", {-420} );
    cout << formatMessage("{{:*<~!#12'h}}  -  |{:*<~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*<+~12x}}    -  |{:*<+~12x}|\n", {-420} );
    cout << formatMessage("{{:*<+~12X}}    -  |{:*<+~12X}|\n", {-420} );
    cout << formatMessage("{{:*<+~12'x}}   -  |{:*<+~12'x}|\n", {-420} );
    cout << formatMessage("{{:*<+~12'X}}   -  |{:*<+~12'X}|\n", {-420} );
    cout << formatMessage("{{:*<+~#12x}}   -  |{:*<+~#12x}|\n", {-420} );
    cout << formatMessage("{{:*<+~#12X}}   -  |{:*<+~#12X}|\n", {-420} );
    cout << formatMessage("{{:*<+~#12h}}   -  |{:*<+~#12h}|\n", {-420} );
    cout << formatMessage("{{:*<+~#12'h}}  -  |{:*<+~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*<+~!#12x}}  -  |{:*<+~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*<+~!#12X}}  -  |{:*<+~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*<+~!#12h}}  -  |{:*<+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*<+~!#12'h}}  -  |{:*<+~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*< ~12x}}    -  |{:*< ~12x}|\n", {-420} );
    cout << formatMessage("{{:*< ~12X}}    -  |{:*< ~12X}|\n", {-420} );
    cout << formatMessage("{{:*< ~12'x}}   -  |{:*< ~12'x}|\n", {-420} );
    cout << formatMessage("{{:*< ~12'X}}   -  |{:*< ~12'X}|\n", {-420} );
    cout << formatMessage("{{:*< ~#12x}}   -  |{:*< ~#12x}|\n", {-420} );
    cout << formatMessage("{{:*< ~#12X}}   -  |{:*< ~#12X}|\n", {-420} );
    cout << formatMessage("{{:*< ~#12h}}   -  |{:*< ~#12h}|\n", {-420} );
    cout << formatMessage("{{:*< ~#12'h}}  -  |{:*< ~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*< ~!#12x}}  -  |{:*< ~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*< ~!#12X}}  -  |{:*< ~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*< ~!#12h}}  -  |{:*< ~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*< ~!#12'h}}  -  |{:*< ~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:>12}}        -  |{:>12}|\n", {-420} );
    cout << formatMessage("{{:>12b}}       -  |{:>12b}|\n", {-420} );
    cout << formatMessage("{{:>12x}}       -  |{:>12x}|\n", {-420} );
    cout << formatMessage("{{:>12X}}       -  |{:>12X}|\n", {-420} );
    cout << formatMessage("{{:>12%}}       -  |{:>12%}|\n", {-420} );
    cout << formatMessage("{{:>#12x}}      -  |{:>#12x}|\n", {-420} );
    cout << formatMessage("{{:>#12X}}      -  |{:>#12X}|\n", {-420} );
    cout << formatMessage("{{:>#12h}}      -  |{:>#12h}|\n", {-420} );
    cout << formatMessage("{{:>!#12x}}     -  |{:>!#12x}|\n", {-420} );
    cout << formatMessage("{{:>!#12X}}     -  |{:>!#12X}|\n", {-420} );
    cout << formatMessage("{{:>!#12h}}     -  |{:>!#12h}|\n", {-420} );
    cout << formatMessage("{{:>+~12x}}     -  |{:>+~12x}|\n", {-420} );
    cout << formatMessage("{{:>+~12X}}     -  |{:>+~12X}|\n", {-420} );
    cout << formatMessage("{{:>+~12'x}}    -  |{:>+~12'x}|\n", {-420} );
    cout << formatMessage("{{:>+~12'X}}    -  |{:>+~12'X}|\n", {-420} );
    cout << formatMessage("{{:>+~#12x}}    -  |{:>+~#12x}|\n", {-420} );
    cout << formatMessage("{{:>+~#12X}}    -  |{:>+~#12X}|\n", {-420} );
    cout << formatMessage("{{:>+~#12h}}    -  |{:>+~#12h}|\n", {-420} );
    cout << formatMessage("{{:>+~#12'h}}   -  |{:>+~#12'h}|\n", {-420} );
    cout << formatMessage("{{:>+~!#12x}}   -  |{:>+~!#12x}|\n", {-420} );
    cout << formatMessage("{{:>+~!#12X}}   -  |{:>+~!#12X}|\n", {-420} );
    cout << formatMessage("{{:>+~!#12h}}   -  |{:>+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:>+~!#12'h}}  -  |{:>+~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*>12}}       -  |{:*>12}|\n", {-420} );
    cout << formatMessage("{{:*>12b}}      -  |{:*>12b}|\n", {-420} );
    cout << formatMessage("{{:*>12x}}      -  |{:*>12x}|\n", {-420} );
    cout << formatMessage("{{:*>12X}}      -  |{:*>12X}|\n", {-420} );
    cout << formatMessage("{{:*>12%}}      -  |{:*>12%}|\n", {-420} );
    cout << formatMessage("{{:*>#12x}}     -  |{:*>#12x}|\n", {-420} );
    cout << formatMessage("{{:*>#12X}}     -  |{:*>#12X}|\n", {-420} );
    cout << formatMessage("{{:*>#12h}}     -  |{:*>#12h}|\n", {-420} );
    cout << formatMessage("{{:*>!#12x}}    -  |{:*>!#12x}|\n", {-420} );
    cout << formatMessage("{{:*>!#12X}}    -  |{:*>!#12X}|\n", {-420} );
    cout << formatMessage("{{:*>!#12h}}    -  |{:*>!#12h}|\n", {-420} );
    cout << formatMessage("{{:*>+~12x}}    -  |{:*>+~12x}|\n", {-420} );
    cout << formatMessage("{{:*>+~12X}}    -  |{:*>+~12X}|\n", {-420} );
    cout << formatMessage("{{:*>+~12'x}}   -  |{:*>+~12'x}|\n", {-420} );
    cout << formatMessage("{{:*>+~12'X}}   -  |{:*>+~12'X}|\n", {-420} );
    cout << formatMessage("{{:*>+~#12x}}   -  |{:*>+~#12x}|\n", {-420} );
    cout << formatMessage("{{:*>+~#12X}}   -  |{:*>+~#12X}|\n", {-420} );
    cout << formatMessage("{{:*>+~#12h}}   -  |{:*>+~#12h}|\n", {-420} );
    cout << formatMessage("{{:*>+~#12'h}}  -  |{:*>+~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*>+~!#12x}}  -  |{:*>+~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*>+~!#12X}}  -  |{:*>+~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*>+~!#12h}}  -  |{:*>+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*>+~!#12'h}}  -  |{:*>+~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*> ~12x}}    -  |{:*> ~12x}|\n", {-420} );
    cout << formatMessage("{{:*> ~12X}}    -  |{:*> ~12X}|\n", {-420} );
    cout << formatMessage("{{:*> ~12'x}}   -  |{:*> ~12'x}|\n", {-420} );
    cout << formatMessage("{{:*> ~12'X}}   -  |{:*> ~12'X}|\n", {-420} );
    cout << formatMessage("{{:*> ~#12x}}   -  |{:*> ~#12x}|\n", {-420} );
    cout << formatMessage("{{:*> ~#12X}}   -  |{:*> ~#12X}|\n", {-420} );
    cout << formatMessage("{{:*> ~#12h}}   -  |{:*> ~#12h}|\n", {-420} );
    cout << formatMessage("{{:*> ~#12'h}}  -  |{:*> ~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*> ~!#12x}}  -  |{:*> ~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*> ~!#12X}}  -  |{:*> ~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*> ~!#12h}}  -  |{:*> ~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*> ~!#12'h}}  -  |{:*> ~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:^12}}        -  |{:^12}|\n", {-420} );
    cout << formatMessage("{{:^12b}}       -  |{:^12b}|\n", {-420} );
    cout << formatMessage("{{:^12x}}       -  |{:^12x}|\n", {-420} );
    cout << formatMessage("{{:^12X}}       -  |{:^12X}|\n", {-420} );
    cout << formatMessage("{{:^12%}}       -  |{:^12%}|\n", {-420} );
    cout << formatMessage("{{:^#12x}}      -  |{:^#12x}|\n", {-420} );
    cout << formatMessage("{{:^#12X}}      -  |{:^#12X}|\n", {-420} );
    cout << formatMessage("{{:^#12h}}      -  |{:^#12h}|\n", {-420} );
    cout << formatMessage("{{:^!#12x}}     -  |{:^!#12x}|\n", {-420} );
    cout << formatMessage("{{:^!#12X}}     -  |{:^!#12X}|\n", {-420} );
    cout << formatMessage("{{:^!#12h}}     -  |{:^!#12h}|\n", {-420} );
    cout << formatMessage("{{:^~12x}}      -  |{:^~12x}|\n", {-420} );
    cout << formatMessage("{{:^~12X}}      -  |{:^~12X}|\n", {-420} );
    cout << formatMessage("{{:^+~12x}}     -  |{:^+~12x}|\n", {-420} );
    cout << formatMessage("{{:^+~12X}}     -  |{:^+~12X}|\n", {-420} );
    cout << formatMessage("{{:^+~12'x}}    -  |{:^+~12'x}|\n", {-420} );
    cout << formatMessage("{{:^+~12'X}}    -  |{:^+~12'X}|\n", {-420} );
    cout << formatMessage("{{:^+~#12h}}    -  |{:^+~#12h}|\n", {-420} );
    cout << formatMessage("{{:^+~!#12h}}   -  |{:^+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:^ ~12'x}}    -  |{:^ ~12'x}|\n", {-420} );
    cout << formatMessage("{{:^ ~12'X}}    -  |{:^ ~12'X}|\n", {-420} );
    cout << formatMessage("{{:^ ~#12h}}    -  |{:^ ~#12h}|\n", {-420} );
    cout << formatMessage("{{:^ ~!#12h}}   -  |{:^ ~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*^12}}       -  |{:*^12}|\n", {-420} );
    cout << formatMessage("{{:*^12b}}      -  |{:*^12b}|\n", {-420} );
    cout << formatMessage("{{:*^12x}}      -  |{:*^12x}|\n", {-420} );
    cout << formatMessage("{{:*^12X}}      -  |{:*^12X}|\n", {-420} );
    cout << formatMessage("{{:*^12%}}      -  |{:*^12%}|\n", {-420} );
    cout << formatMessage("{{:*^#12x}}     -  |{:*^#12x}|\n", {-420} );
    cout << formatMessage("{{:*^#12X}}     -  |{:*^#12X}|\n", {-420} );
    cout << formatMessage("{{:*^#12h}}     -  |{:*^#12h}|\n", {-420} );
    cout << formatMessage("{{:*^!#12x}}    -  |{:*^!#12x}|\n", {-420} );
    cout << formatMessage("{{:*^!#12X}}    -  |{:*^!#12X}|\n", {-420} );
    cout << formatMessage("{{:*^!#12h}}    -  |{:*^!#12h}|\n", {-420} );
    cout << formatMessage("{{:*^~12x}}     -  |{:*^~12x}|\n", {-420} );
    cout << formatMessage("{{:*^~12X}}     -  |{:*^~12X}|\n", {-420} );
    cout << formatMessage("{{:*^~12'x}}    -  |{:*^~12'x}|\n", {-420} );
    cout << formatMessage("{{:*^~12'X}}    -  |{:*^~12'X}|\n", {-420} );
    cout << formatMessage("{{:*^~#12x}}    -  |{:*^~#12x}|\n", {-420} );
    cout << formatMessage("{{:*^~#12X}}    -  |{:*^~#12X}|\n", {-420} );
    cout << formatMessage("{{:*^~#12h}}    -  |{:*^~#12h}|\n", {-420} );
    cout << formatMessage("{{:*^~#12'h}}   -  |{:*^~#12'h}|\n", {-420} );
    cout << formatMessage("{{:*^~!#12x}}   -  |{:*^~!#12x}|\n", {-420} );
    cout << formatMessage("{{:*^~!#12X}}   -  |{:*^~!#12X}|\n", {-420} );
    cout << formatMessage("{{:*^~!#12h}}   -  |{:*^~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*^~!#12'h}}  -  |{:*^~!#12'h}|\n", {-420} );
    cout << formatMessage("{{:*^+~12x}}    -  |{:*^+~12x}|\n", {-420} );
    cout << formatMessage("{{:*^+~12X}}    -  |{:*^+~12X}|\n", {-420} );
    cout << formatMessage("{{:*^+~12'x}}   -  |{:*^+~12'x}|\n", {-420} );
    cout << formatMessage("{{:*^+~12'X}}   -  |{:*^+~12'X}|\n", {-420} );
    cout << formatMessage("{{:*^+~#12h}}   -  |{:*^+~#12h}|\n", {-420} );
    cout << formatMessage("{{:*^+~!#12h}}  -  |{:*^+~!#12h}|\n", {-420} );
    cout << formatMessage("{{:*^ ~12x}}    -  |{:*^ ~12x}|\n", {-420} );
    cout << formatMessage("{{:*^ ~12X}}    -  |{:*^ ~12X}|\n", {-420} );
    cout << formatMessage("{{:*^ ~12'x}}   -  |{:*^ ~12'x}|\n", {-420} );
    cout << formatMessage("{{:*^ ~12'X}}   -  |{:*^ ~12'X}|\n", {-420} );
    cout << formatMessage("{{:*^ ~#12h}}   -  |{:*^ ~#12h}|\n", {-420} );
    cout << formatMessage("{{:*^ ~!#12h}}  -  |{:*^ ~!#12h}|\n", {-420} );
    cout << formatMessage("{{:0}}          -  |{:0}|\n", {420} );
    cout << formatMessage("{{:0b}}         -  |{:0b}|\n", {420} );
    cout << formatMessage("{{:0x}}         -  |{:0x}|\n", {420} );
    cout << formatMessage("{{:0X}}         -  |{:0X}|\n", {420} );
    cout << formatMessage("{{:0%}}         -  |{:0%}|\n", {420} );
    cout << formatMessage("{{:0'b}}        -  |{:0'b}|\n", {420} );
    cout << formatMessage("{{:0'x}}        -  |{:0'x}|\n", {420} );
    cout << formatMessage("{{:0'X}}        -  |{:0'X}|\n", {420} );
    cout << formatMessage("{{:12}}         -  |{:12}|\n", {420} );
    cout << formatMessage("{{:12b}}        -  |{:12b}|\n", {420} );
    cout << formatMessage("{{:12x}}        -  |{:12x}|\n", {420} );
    cout << formatMessage("{{:12X}}        -  |{:12X}|\n", {420} );
    cout << formatMessage("{{:12%}}        -  |{:12%}|\n", {420} );
    cout << formatMessage("{{:12'b}}       -  |{:12'b}|\n", {420} );
    cout << formatMessage("{{:#0b}}        -  |{:#0b}|\n", {420} );
    cout << formatMessage("{{:#0x}}        -  |{:#0x}|\n", {420} );
    cout << formatMessage("{{:#0X}}        -  |{:#0X}|\n", {420} );
    cout << formatMessage("{{:#0h}}        -  |{:#0h}|\n", {420} );
    cout << formatMessage("{{:#0'b}}       -  |{:#0'b}|\n", {420} );
    cout << formatMessage("{{:#0'x}}       -  |{:#0'x}|\n", {420} );
    cout << formatMessage("{{:#0'X}}       -  |{:#0'X}|\n", {420} );
    cout << formatMessage("{{:#0'h}}       -  |{:#0'h}|\n", {420} );
    cout << formatMessage("{{:#12b}}       -  |{:#12b}|\n", {420} );
    cout << formatMessage("{{:#12x}}       -  |{:#12x}|\n", {420} );
    cout << formatMessage("{{:#12X}}       -  |{:#12X}|\n", {420} );
    cout << formatMessage("{{:#12h}}       -  |{:#12h}|\n", {420} );
    cout << formatMessage("{{:#12'b}}      -  |{:#12'b}|\n", {420} );
    cout << formatMessage("{{:012}}        -  |{:012}|\n", {420} );
    cout << formatMessage("{{:012b}}       -  |{:012b}|\n", {420} );
    cout << formatMessage("{{:012x}}       -  |{:012x}|\n", {420} );
    cout << formatMessage("{{:012X}}       -  |{:012X}|\n", {420} );
    cout << formatMessage("{{:012%}}       -  |{:012%}|\n", {420} );
    cout << formatMessage("{{:012'}}       -  |{:012'}|\n", {420} );
    cout << formatMessage("{{:012'b}}      -  |{:012'b}|\n", {420} );
    cout << formatMessage("{{:012'x}}      -  |{:012'x}|\n", {420} );
    cout << formatMessage("{{:012'X}}      -  |{:012'X}|\n", {420} );
    cout << formatMessage("{{:012'%}}      -  |{:012'%}|\n", {420} );
    cout << formatMessage("{{:#012b}}      -  |{:#012b}|\n", {420} );
    cout << formatMessage("{{:#012x}}      -  |{:#012x}|\n", {420} );
    cout << formatMessage("{{:#012X}}      -  |{:#012X}|\n", {420} );
    cout << formatMessage("{{:#012h}}      -  |{:#012h}|\n", {420} );
    cout << formatMessage("{{:#012'x}}     -  |{:#012'x}|\n", {420} );
    cout << formatMessage("{{:#012'X}}     -  |{:#012'X}|\n", {420} );
    cout << formatMessage("{{:#012'h}}     -  |{:#012'h}|\n", {420} );
    cout << formatMessage("{{:!#0b}}       -  |{:!#0b}|\n", {420} );
    cout << formatMessage("{{:!#0x}}       -  |{:!#0x}|\n", {420} );
    cout << formatMessage("{{:!#0X}}       -  |{:!#0X}|\n", {420} );
    cout << formatMessage("{{:!#0h}}       -  |{:!#0h}|\n", {420} );
    cout << formatMessage("{{:!#0'b}}      -  |{:!#0'b}|\n", {420} );
    cout << formatMessage("{{:!#0'x}}      -  |{:!#0'x}|\n", {420} );
    cout << formatMessage("{{:!#0'X}}      -  |{:!#0'X}|\n", {420} );
    cout << formatMessage("{{:!#0'h}}      -  |{:!#0'h}|\n", {420} );
    cout << formatMessage("{{:!#12b}}      -  |{:!#12b}|\n", {420} );
    cout << formatMessage("{{:!#12x}}      -  |{:!#12x}|\n", {420} );
    cout << formatMessage("{{:!#12X}}      -  |{:!#12X}|\n", {420} );
    cout << formatMessage("{{:!#12h}}      -  |{:!#12h}|\n", {420} );
    cout << formatMessage("{{:!#12'b}}     -  |{:!#12'b}|\n", {420} );
    cout << formatMessage("{{:!#012b}}     -  |{:!#012b}|\n", {420} );
    cout << formatMessage("{{:!#012x}}     -  |{:!#012x}|\n", {420} );
    cout << formatMessage("{{:!#012X}}     -  |{:!#012X}|\n", {420} );
    cout << formatMessage("{{:!#012h}}     -  |{:!#012h}|\n", {420} );
    cout << formatMessage("{{:!#012'x}}    -  |{:!#012'x}|\n", {420} );
    cout << formatMessage("{{:!#012'X}}    -  |{:!#012'X}|\n", {420} );
    cout << formatMessage("{{:!#012'h}}    -  |{:!#012'h}|\n", {420} );
    cout << formatMessage("{{:+0}}         -  |{:+0}|\n", {420} );
    cout << formatMessage("{{:+0b}}        -  |{:+0b}|\n", {420} );
    cout << formatMessage("{{:+0x}}        -  |{:+0x}|\n", {420} );
    cout << formatMessage("{{:+0X}}        -  |{:+0X}|\n", {420} );
    cout << formatMessage("{{:+0%}}        -  |{:+0%}|\n", {420} );
    cout << formatMessage("{{:+0'b}}       -  |{:+0'b}|\n", {420} );
    cout << formatMessage("{{:+0'x}}       -  |{:+0'x}|\n", {420} );
    cout << formatMessage("{{:+0'X}}       -  |{:+0'X}|\n", {420} );
    cout << formatMessage("{{:+12}}        -  |{:+12}|\n", {420} );
    cout << formatMessage("{{:+12b}}       -  |{:+12b}|\n", {420} );
    cout << formatMessage("{{:+12x}}       -  |{:+12x}|\n", {420} );
    cout << formatMessage("{{:+12X}}       -  |{:+12X}|\n", {420} );
    cout << formatMessage("{{:+12%}}       -  |{:+12%}|\n", {420} );
    cout << formatMessage("{{:+12'b}}      -  |{:+12'b}|\n", {420} );
    cout << formatMessage("{{:+#0b}}       -  |{:+#0b}|\n", {420} );
    cout << formatMessage("{{:+#0x}}       -  |{:+#0x}|\n", {420} );
    cout << formatMessage("{{:+#0X}}       -  |{:+#0X}|\n", {420} );
    cout << formatMessage("{{:+#0h}}       -  |{:+#0h}|\n", {420} );
    cout << formatMessage("{{:+#0'b}}      -  |{:+#0'b}|\n", {420} );
    cout << formatMessage("{{:+#0'x}}      -  |{:+#0'x}|\n", {420} );
    cout << formatMessage("{{:+#0'X}}      -  |{:+#0'X}|\n", {420} );
    cout << formatMessage("{{:+#0'h}}      -  |{:+#0'h}|\n", {420} );
    cout << formatMessage("{{:+#12b}}      -  |{:+#12b}|\n", {420} );
    cout << formatMessage("{{:+#12x}}      -  |{:+#12x}|\n", {420} );
    cout << formatMessage("{{:+#12X}}      -  |{:+#12X}|\n", {420} );
    cout << formatMessage("{{:+#12h}}      -  |{:+#12h}|\n", {420} );
    cout << formatMessage("{{:+#12'b}}     -  |{:+#12'b}|\n", {420} );
    cout << formatMessage("{{:+012}}       -  |{:+012}|\n", {420} );
    cout << formatMessage("{{:+012b}}      -  |{:+012b}|\n", {420} );
    cout << formatMessage("{{:+012x}}      -  |{:+012x}|\n", {420} );
    cout << formatMessage("{{:+012X}}      -  |{:+012X}|\n", {420} );
    cout << formatMessage("{{:+012%}}      -  |{:+012%}|\n", {420} );
    cout << formatMessage("{{:+012'}}      -  |{:+012'}|\n", {420} );
    cout << formatMessage("{{:+012'x}}     -  |{:+012'x}|\n", {420} );
    cout << formatMessage("{{:+012'X}}     -  |{:+012'X}|\n", {420} );
    cout << formatMessage("{{:+012'%}}     -  |{:+012'%}|\n", {420} );
    cout << formatMessage("{{:+#012x}}     -  |{:+#012x}|\n", {420} );
    cout << formatMessage("{{:+#012X}}     -  |{:+#012X}|\n", {420} );
    cout << formatMessage("{{:+#012h}}     -  |{:+#012h}|\n", {420} );
    cout << formatMessage("{{:+#012'h}}    -  |{:+#012'h}|\n", {420} );
    cout << formatMessage("{{:+!#0b}}      -  |{:+!#0b}|\n", {420} );
    cout << formatMessage("{{:+!#0x}}      -  |{:+!#0x}|\n", {420} );
    cout << formatMessage("{{:+!#0X}}      -  |{:+!#0X}|\n", {420} );
    cout << formatMessage("{{:+!#0h}}      -  |{:+!#0h}|\n", {420} );
    cout << formatMessage("{{:+!#0'b}}     -  |{:+!#0'b}|\n", {420} );
    cout << formatMessage("{{:+!#0'x}}     -  |{:+!#0'x}|\n", {420} );
    cout << formatMessage("{{:+!#0'X}}     -  |{:+!#0'X}|\n", {420} );
    cout << formatMessage("{{:+!#0'h}}     -  |{:+!#0'h}|\n", {420} );
    cout << formatMessage("{{:+!#12b}}     -  |{:+!#12b}|\n", {420} );
    cout << formatMessage("{{:+!#12x}}     -  |{:+!#12x}|\n", {420} );
    cout << formatMessage("{{:+!#12X}}     -  |{:+!#12X}|\n", {420} );
    cout << formatMessage("{{:+!#12h}}     -  |{:+!#12h}|\n", {420} );
    cout << formatMessage("{{:+!#12'b}}    -  |{:+!#12'b}|\n", {420} );
    cout << formatMessage("{{:+!#012x}}    -  |{:+!#012x}|\n", {420} );
    cout << formatMessage("{{:+!#012X}}    -  |{:+!#012X}|\n", {420} );
    cout << formatMessage("{{:+!#012h}}    -  |{:+!#012h}|\n", {420} );
    cout << formatMessage("{{:+!#012'h}}   -  |{:+!#012'h}|\n", {420} );
    cout << formatMessage("{{:=12}}        -  |{:=12}|\n", {420} );
    cout << formatMessage("{{:=12b}}       -  |{:=12b}|\n", {420} );
    cout << formatMessage("{{:=12x}}       -  |{:=12x}|\n", {420} );
    cout << formatMessage("{{:=12X}}       -  |{:=12X}|\n", {420} );
    cout << formatMessage("{{:=12%}}       -  |{:=12%}|\n", {420} );
    cout << formatMessage("{{:=12'b}}      -  |{:=12'b}|\n", {420} );
    cout << formatMessage("{{:=#12b}}      -  |{:=#12b}|\n", {420} );
    cout << formatMessage("{{:=#12x}}      -  |{:=#12x}|\n", {420} );
    cout << formatMessage("{{:=#12X}}      -  |{:=#12X}|\n", {420} );
    cout << formatMessage("{{:=#12h}}      -  |{:=#12h}|\n", {420} );
    cout << formatMessage("{{:=!#12b}}     -  |{:=!#12b}|\n", {420} );
    cout << formatMessage("{{:=!#12x}}     -  |{:=!#12x}|\n", {420} );
    cout << formatMessage("{{:=!#12X}}     -  |{:=!#12X}|\n", {420} );
    cout << formatMessage("{{:=!#12h}}     -  |{:=!#12h}|\n", {420} );
    cout << formatMessage("{{:=+12}}       -  |{:=+12}|\n", {420} );
    cout << formatMessage("{{:=+12b}}      -  |{:=+12b}|\n", {420} );
    cout << formatMessage("{{:=+12x}}      -  |{:=+12x}|\n", {420} );
    cout << formatMessage("{{:=+12X}}      -  |{:=+12X}|\n", {420} );
    cout << formatMessage("{{:=+12%}}      -  |{:=+12%}|\n", {420} );
    cout << formatMessage("{{:=+#12x}}     -  |{:=+#12x}|\n", {420} );
    cout << formatMessage("{{:=+#12X}}     -  |{:=+#12X}|\n", {420} );
    cout << formatMessage("{{:=+#12h}}     -  |{:=+#12h}|\n", {420} );
    cout << formatMessage("{{:=+!#12x}}    -  |{:=+!#12x}|\n", {420} );
    cout << formatMessage("{{:=+!#12X}}    -  |{:=+!#12X}|\n", {420} );
    cout << formatMessage("{{:=+!#12h}}    -  |{:=+!#12h}|\n", {420} );
    cout << formatMessage("{{:= 0}}        -  |{:= 0}|\n", {420} );
    cout << formatMessage("{{:= 0b}}       -  |{:= 0b}|\n", {420} );
    cout << formatMessage("{{:= 0x}}       -  |{:= 0x}|\n", {420} );
    cout << formatMessage("{{:= 0X}}       -  |{:= 0X}|\n", {420} );
    cout << formatMessage("{{:= 0%}}       -  |{:= 0%}|\n", {420} );
    cout << formatMessage("{{:= 0'b}}      -  |{:= 0'b}|\n", {420} );
    cout << formatMessage("{{:= 0'x}}      -  |{:= 0'x}|\n", {420} );
    cout << formatMessage("{{:= 0'X}}      -  |{:= 0'X}|\n", {420} );
    cout << formatMessage("{{:= #0b}}      -  |{:= #0b}|\n", {420} );
    cout << formatMessage("{{:= #0x}}      -  |{:= #0x}|\n", {420} );
    cout << formatMessage("{{:= #0X}}      -  |{:= #0X}|\n", {420} );
    cout << formatMessage("{{:= #0h}}      -  |{:= #0h}|\n", {420} );
    cout << formatMessage("{{:= #0'b}}     -  |{:= #0'b}|\n", {420} );
    cout << formatMessage("{{:= #0'x}}     -  |{:= #0'x}|\n", {420} );
    cout << formatMessage("{{:= #0'X}}     -  |{:= #0'X}|\n", {420} );
    cout << formatMessage("{{:= #0'h}}     -  |{:= #0'h}|\n", {420} );
    cout << formatMessage("{{:= #12'b}}    -  |{:= #12'b}|\n", {420} );
    cout << formatMessage("{{:= 012}}      -  |{:= 012}|\n", {420} );
    cout << formatMessage("{{:= 012b}}     -  |{:= 012b}|\n", {420} );
    cout << formatMessage("{{:= 012x}}     -  |{:= 012x}|\n", {420} );
    cout << formatMessage("{{:= 012X}}     -  |{:= 012X}|\n", {420} );
    cout << formatMessage("{{:= 012%}}     -  |{:= 012%}|\n", {420} );
    cout << formatMessage("{{:= 012'}}     -  |{:= 012'}|\n", {420} );
    cout << formatMessage("{{:= 012'x}}    -  |{:= 012'x}|\n", {420} );
    cout << formatMessage("{{:= 012'X}}    -  |{:= 012'X}|\n", {420} );
    cout << formatMessage("{{:= 012'%}}    -  |{:= 012'%}|\n", {420} );
    cout << formatMessage("{{:= #012x}}    -  |{:= #012x}|\n", {420} );
    cout << formatMessage("{{:= #012X}}    -  |{:= #012X}|\n", {420} );
    cout << formatMessage("{{:= #012h}}    -  |{:= #012h}|\n", {420} );
    cout << formatMessage("{{:= #012'h}}   -  |{:= #012'h}|\n", {420} );
    cout << formatMessage("{{:= !#0b}}     -  |{:= !#0b}|\n", {420} );
    cout << formatMessage("{{:= !#0x}}     -  |{:= !#0x}|\n", {420} );
    cout << formatMessage("{{:= !#0X}}     -  |{:= !#0X}|\n", {420} );
    cout << formatMessage("{{:= !#0h}}     -  |{:= !#0h}|\n", {420} );
    cout << formatMessage("{{:= !#0'b}}    -  |{:= !#0'b}|\n", {420} );
    cout << formatMessage("{{:= !#0'x}}    -  |{:= !#0'x}|\n", {420} );
    cout << formatMessage("{{:= !#0'X}}    -  |{:= !#0'X}|\n", {420} );
    cout << formatMessage("{{:= !#0'h}}    -  |{:= !#0'h}|\n", {420} );
    cout << formatMessage("{{:= !#12'b}}   -  |{:= !#12'b}|\n", {420} );
    cout << formatMessage("{{:= !#012x}}   -  |{:= !#012x}|\n", {420} );
    cout << formatMessage("{{:= !#012X}}   -  |{:= !#012X}|\n", {420} );
    cout << formatMessage("{{:= !#012h}}   -  |{:= !#012h}|\n", {420} );
    cout << formatMessage("{{:= !#012'h}}  -  |{:= !#012'h}|\n", {420} );
    cout << formatMessage("{{:*=12}}       -  |{:*=12}|\n", {420} );
    cout << formatMessage("{{:*=12b}}      -  |{:*=12b}|\n", {420} );
    cout << formatMessage("{{:*=12x}}      -  |{:*=12x}|\n", {420} );
    cout << formatMessage("{{:*=12X}}      -  |{:*=12X}|\n", {420} );
    cout << formatMessage("{{:*=12%}}      -  |{:*=12%}|\n", {420} );
    cout << formatMessage("{{:*=12'b}}     -  |{:*=12'b}|\n", {420} );
    cout << formatMessage("{{:*=#12b}}     -  |{:*=#12b}|\n", {420} );
    cout << formatMessage("{{:*=#12x}}     -  |{:*=#12x}|\n", {420} );
    cout << formatMessage("{{:*=#12X}}     -  |{:*=#12X}|\n", {420} );
    cout << formatMessage("{{:*=#12h}}     -  |{:*=#12h}|\n", {420} );
    cout << formatMessage("{{:*=!#12b}}    -  |{:*=!#12b}|\n", {420} );
    cout << formatMessage("{{:*=!#12x}}    -  |{:*=!#12x}|\n", {420} );
    cout << formatMessage("{{:*=!#12X}}    -  |{:*=!#12X}|\n", {420} );
    cout << formatMessage("{{:*=!#12h}}    -  |{:*=!#12h}|\n", {420} );
    cout << formatMessage("{{:*=+12}}      -  |{:*=+12}|\n", {420} );
    cout << formatMessage("{{:*=+12b}}     -  |{:*=+12b}|\n", {420} );
    cout << formatMessage("{{:*=+12x}}     -  |{:*=+12x}|\n", {420} );
    cout << formatMessage("{{:*=+12X}}     -  |{:*=+12X}|\n", {420} );
    cout << formatMessage("{{:*=+12%}}     -  |{:*=+12%}|\n", {420} );
    cout << formatMessage("{{:*=+#12x}}    -  |{:*=+#12x}|\n", {420} );
    cout << formatMessage("{{:*=+#12X}}    -  |{:*=+#12X}|\n", {420} );
    cout << formatMessage("{{:*=+#12h}}    -  |{:*=+#12h}|\n", {420} );
    cout << formatMessage("{{:*=+!#12x}}   -  |{:*=+!#12x}|\n", {420} );
    cout << formatMessage("{{:*=+!#12X}}   -  |{:*=+!#12X}|\n", {420} );
    cout << formatMessage("{{:*=+!#12h}}   -  |{:*=+!#12h}|\n", {420} );
    cout << formatMessage("{{:*= 12}}      -  |{:*= 12}|\n", {420} );
    cout << formatMessage("{{:*= 12b}}     -  |{:*= 12b}|\n", {420} );
    cout << formatMessage("{{:*= 12x}}     -  |{:*= 12x}|\n", {420} );
    cout << formatMessage("{{:*= 12X}}     -  |{:*= 12X}|\n", {420} );
    cout << formatMessage("{{:*= 12%}}     -  |{:*= 12%}|\n", {420} );
    cout << formatMessage("{{:*= #12x}}    -  |{:*= #12x}|\n", {420} );
    cout << formatMessage("{{:*= #12X}}    -  |{:*= #12X}|\n", {420} );
    cout << formatMessage("{{:*= #12h}}    -  |{:*= #12h}|\n", {420} );
    cout << formatMessage("{{:*= !#12x}}   -  |{:*= !#12x}|\n", {420} );
    cout << formatMessage("{{:*= !#12X}}   -  |{:*= !#12X}|\n", {420} );
    cout << formatMessage("{{:*= !#12h}}   -  |{:*= !#12h}|\n", {420} );
    cout << formatMessage("{{:<0b}}        -  |{:<0b}|\n", {420} );
    cout << formatMessage("{{:<0x}}        -  |{:<0x}|\n", {420} );
    cout << formatMessage("{{:<0X}}        -  |{:<0X}|\n", {420} );
    cout << formatMessage("{{:<0'b}}       -  |{:<0'b}|\n", {420} );
    cout << formatMessage("{{:<#0b}}       -  |{:<#0b}|\n", {420} );
    cout << formatMessage("{{:<#0x}}       -  |{:<#0x}|\n", {420} );
    cout << formatMessage("{{:<#0X}}       -  |{:<#0X}|\n", {420} );
    cout << formatMessage("{{:<#0h}}       -  |{:<#0h}|\n", {420} );
    cout << formatMessage("{{:<!#0b}}      -  |{:<!#0b}|\n", {420} );
    cout << formatMessage("{{:<!#0x}}      -  |{:<!#0x}|\n", {420} );
    cout << formatMessage("{{:<!#0X}}      -  |{:<!#0X}|\n", {420} );
    cout << formatMessage("{{:<!#0h}}      -  |{:<!#0h}|\n", {420} );
    cout << formatMessage("{{:<+0b}}       -  |{:<+0b}|\n", {420} );
    cout << formatMessage("{{:<+0x}}       -  |{:<+0x}|\n", {420} );
    cout << formatMessage("{{:<+0X}}       -  |{:<+0X}|\n", {420} );
    cout << formatMessage("{{:<+#0x}}      -  |{:<+#0x}|\n", {420} );
    cout << formatMessage("{{:<+#0X}}      -  |{:<+#0X}|\n", {420} );
    cout << formatMessage("{{:<+#0h}}      -  |{:<+#0h}|\n", {420} );
    cout << formatMessage("{{:<+!#0x}}     -  |{:<+!#0x}|\n", {420} );
    cout << formatMessage("{{:<+!#0X}}     -  |{:<+!#0X}|\n", {420} );
    cout << formatMessage("{{:<+!#0h}}     -  |{:<+!#0h}|\n", {420} );
    cout << formatMessage("{{:< 0b}}       -  |{:< 0b}|\n", {420} );
    cout << formatMessage("{{:< 0x}}       -  |{:< 0x}|\n", {420} );
    cout << formatMessage("{{:< 0X}}       -  |{:< 0X}|\n", {420} );
    cout << formatMessage("{{:< 12}}       -  |{:< 12}|\n", {420} );
    cout << formatMessage("{{:< 12b}}      -  |{:< 12b}|\n", {420} );
    cout << formatMessage("{{:< 12x}}      -  |{:< 12x}|\n", {420} );
    cout << formatMessage("{{:< 12X}}      -  |{:< 12X}|\n", {420} );
    cout << formatMessage("{{:< 12%}}      -  |{:< 12%}|\n", {420} );
    cout << formatMessage("{{:< #0x}}      -  |{:< #0x}|\n", {420} );
    cout << formatMessage("{{:< #0X}}      -  |{:< #0X}|\n", {420} );
    cout << formatMessage("{{:< #0h}}      -  |{:< #0h}|\n", {420} );
    cout << formatMessage("{{:< #12x}}     -  |{:< #12x}|\n", {420} );
    cout << formatMessage("{{:< #12X}}     -  |{:< #12X}|\n", {420} );
    cout << formatMessage("{{:< #12h}}     -  |{:< #12h}|\n", {420} );
    cout << formatMessage("{{:< !#0x}}     -  |{:< !#0x}|\n", {420} );
    cout << formatMessage("{{:< !#0X}}     -  |{:< !#0X}|\n", {420} );
    cout << formatMessage("{{:< !#0h}}     -  |{:< !#0h}|\n", {420} );
    cout << formatMessage("{{:< !#12x}}    -  |{:< !#12x}|\n", {420} );
    cout << formatMessage("{{:< !#12X}}    -  |{:< !#12X}|\n", {420} );
    cout << formatMessage("{{:< !#12h}}    -  |{:< !#12h}|\n", {420} );
    cout << formatMessage("{{:*<12}}       -  |{:*<12}|\n", {420} );
    cout << formatMessage("{{:*<12b}}      -  |{:*<12b}|\n", {420} );
    cout << formatMessage("{{:*<12x}}      -  |{:*<12x}|\n", {420} );
    cout << formatMessage("{{:*<12X}}      -  |{:*<12X}|\n", {420} );
    cout << formatMessage("{{:*<12%}}      -  |{:*<12%}|\n", {420} );
    cout << formatMessage("{{:*<12'b}}     -  |{:*<12'b}|\n", {420} );
    cout << formatMessage("{{:*<#12b}}     -  |{:*<#12b}|\n", {420} );
    cout << formatMessage("{{:*<#12x}}     -  |{:*<#12x}|\n", {420} );
    cout << formatMessage("{{:*<#12X}}     -  |{:*<#12X}|\n", {420} );
    cout << formatMessage("{{:*<#12h}}     -  |{:*<#12h}|\n", {420} );
    cout << formatMessage("{{:*<!#12b}}    -  |{:*<!#12b}|\n", {420} );
    cout << formatMessage("{{:*<!#12x}}    -  |{:*<!#12x}|\n", {420} );
    cout << formatMessage("{{:*<!#12X}}    -  |{:*<!#12X}|\n", {420} );
    cout << formatMessage("{{:*<!#12h}}    -  |{:*<!#12h}|\n", {420} );
    cout << formatMessage("{{:*<+12}}      -  |{:*<+12}|\n", {420} );
    cout << formatMessage("{{:*<+12b}}     -  |{:*<+12b}|\n", {420} );
    cout << formatMessage("{{:*<+12x}}     -  |{:*<+12x}|\n", {420} );
    cout << formatMessage("{{:*<+12X}}     -  |{:*<+12X}|\n", {420} );
    cout << formatMessage("{{:*<+12%}}     -  |{:*<+12%}|\n", {420} );
    cout << formatMessage("{{:*<+#12x}}    -  |{:*<+#12x}|\n", {420} );
    cout << formatMessage("{{:*<+#12X}}    -  |{:*<+#12X}|\n", {420} );
    cout << formatMessage("{{:*<+#12h}}    -  |{:*<+#12h}|\n", {420} );
    cout << formatMessage("{{:*<+!#12x}}   -  |{:*<+!#12x}|\n", {420} );
    cout << formatMessage("{{:*<+!#12X}}   -  |{:*<+!#12X}|\n", {420} );
    cout << formatMessage("{{:*<+!#12h}}   -  |{:*<+!#12h}|\n", {420} );
    cout << formatMessage("{{:*< 12}}      -  |{:*< 12}|\n", {420} );
    cout << formatMessage("{{:*< 12b}}     -  |{:*< 12b}|\n", {420} );
    cout << formatMessage("{{:*< 12x}}     -  |{:*< 12x}|\n", {420} );
    cout << formatMessage("{{:*< 12X}}     -  |{:*< 12X}|\n", {420} );
    cout << formatMessage("{{:*< 12%}}     -  |{:*< 12%}|\n", {420} );
    cout << formatMessage("{{:*< #12x}}    -  |{:*< #12x}|\n", {420} );
    cout << formatMessage("{{:*< #12X}}    -  |{:*< #12X}|\n", {420} );
    cout << formatMessage("{{:*< #12h}}    -  |{:*< #12h}|\n", {420} );
    cout << formatMessage("{{:*< !#12x}}   -  |{:*< !#12x}|\n", {420} );
    cout << formatMessage("{{:*< !#12X}}   -  |{:*< !#12X}|\n", {420} );
    cout << formatMessage("{{:*< !#12h}}   -  |{:*< !#12h}|\n", {420} );
    cout << formatMessage("{{:>+12}}       -  |{:>+12}|\n", {420} );
    cout << formatMessage("{{:>+12b}}      -  |{:>+12b}|\n", {420} );
    cout << formatMessage("{{:>+12x}}      -  |{:>+12x}|\n", {420} );
    cout << formatMessage("{{:>+12X}}      -  |{:>+12X}|\n", {420} );
    cout << formatMessage("{{:>+12%}}      -  |{:>+12%}|\n", {420} );
    cout << formatMessage("{{:>+#12x}}     -  |{:>+#12x}|\n", {420} );
    cout << formatMessage("{{:>+#12X}}     -  |{:>+#12X}|\n", {420} );
    cout << formatMessage("{{:>+#12h}}     -  |{:>+#12h}|\n", {420} );
    cout << formatMessage("{{:>+!#12x}}    -  |{:>+!#12x}|\n", {420} );
    cout << formatMessage("{{:>+!#12X}}    -  |{:>+!#12X}|\n", {420} );
    cout << formatMessage("{{:>+!#12h}}    -  |{:>+!#12h}|\n", {420} );
    cout << formatMessage("{{:*>+12}}      -  |{:*>+12}|\n", {420} );
    cout << formatMessage("{{:*>+12b}}     -  |{:*>+12b}|\n", {420} );
    cout << formatMessage("{{:*>+12x}}     -  |{:*>+12x}|\n", {420} );
    cout << formatMessage("{{:*>+12X}}     -  |{:*>+12X}|\n", {420} );
    cout << formatMessage("{{:*>+12%}}     -  |{:*>+12%}|\n", {420} );
    cout << formatMessage("{{:*>+#12x}}    -  |{:*>+#12x}|\n", {420} );
    cout << formatMessage("{{:*>+#12X}}    -  |{:*>+#12X}|\n", {420} );
    cout << formatMessage("{{:*>+#12h}}    -  |{:*>+#12h}|\n", {420} );
    cout << formatMessage("{{:*>+!#12x}}   -  |{:*>+!#12x}|\n", {420} );
    cout << formatMessage("{{:*>+!#12X}}   -  |{:*>+!#12X}|\n", {420} );
    cout << formatMessage("{{:*>+!#12h}}   -  |{:*>+!#12h}|\n", {420} );
    cout << formatMessage("{{:*> 12}}      -  |{:*> 12}|\n", {420} );
    cout << formatMessage("{{:*> 12b}}     -  |{:*> 12b}|\n", {420} );
    cout << formatMessage("{{:*> 12x}}     -  |{:*> 12x}|\n", {420} );
    cout << formatMessage("{{:*> 12X}}     -  |{:*> 12X}|\n", {420} );
    cout << formatMessage("{{:*> 12%}}     -  |{:*> 12%}|\n", {420} );
    cout << formatMessage("{{:*> #12x}}    -  |{:*> #12x}|\n", {420} );
    cout << formatMessage("{{:*> #12X}}    -  |{:*> #12X}|\n", {420} );
    cout << formatMessage("{{:*> #12h}}    -  |{:*> #12h}|\n", {420} );
    cout << formatMessage("{{:*> !#12x}}   -  |{:*> !#12x}|\n", {420} );
    cout << formatMessage("{{:*> !#12X}}   -  |{:*> !#12X}|\n", {420} );
    cout << formatMessage("{{:*> !#12h}}   -  |{:*> !#12h}|\n", {420} );
    cout << formatMessage("{{:^12}}        -  |{:^12}|\n", {420} );
    cout << formatMessage("{{:^12x}}       -  |{:^12x}|\n", {420} );
    cout << formatMessage("{{:^12X}}       -  |{:^12X}|\n", {420} );
    cout << formatMessage("{{:^12%}}       -  |{:^12%}|\n", {420} );
    cout << formatMessage("{{:^#12x}}      -  |{:^#12x}|\n", {420} );
    cout << formatMessage("{{:^#12X}}      -  |{:^#12X}|\n", {420} );
    cout << formatMessage("{{:^#12h}}      -  |{:^#12h}|\n", {420} );
    cout << formatMessage("{{:^!#12x}}     -  |{:^!#12x}|\n", {420} );
    cout << formatMessage("{{:^!#12X}}     -  |{:^!#12X}|\n", {420} );
    cout << formatMessage("{{:^!#12h}}     -  |{:^!#12h}|\n", {420} );
    cout << formatMessage("{{:^+12}}       -  |{:^+12}|\n", {420} );
    cout << formatMessage("{{:^+12b}}      -  |{:^+12b}|\n", {420} );
    cout << formatMessage("{{:^+12x}}      -  |{:^+12x}|\n", {420} );
    cout << formatMessage("{{:^+12X}}      -  |{:^+12X}|\n", {420} );
    cout << formatMessage("{{:^+12%}}      -  |{:^+12%}|\n", {420} );
    cout << formatMessage("{{:^+#12x}}     -  |{:^+#12x}|\n", {420} );
    cout << formatMessage("{{:^+#12X}}     -  |{:^+#12X}|\n", {420} );
    cout << formatMessage("{{:^+#12h}}     -  |{:^+#12h}|\n", {420} );
    cout << formatMessage("{{:^+!#12x}}    -  |{:^+!#12x}|\n", {420} );
    cout << formatMessage("{{:^+!#12X}}    -  |{:^+!#12X}|\n", {420} );
    cout << formatMessage("{{:^+!#12h}}    -  |{:^+!#12h}|\n", {420} );
    cout << formatMessage("{{:^ 12}}       -  |{:^ 12}|\n", {420} );
    cout << formatMessage("{{:^ 12b}}      -  |{:^ 12b}|\n", {420} );
    cout << formatMessage("{{:^ 12x}}      -  |{:^ 12x}|\n", {420} );
    cout << formatMessage("{{:^ 12X}}      -  |{:^ 12X}|\n", {420} );
    cout << formatMessage("{{:^ #12x}}     -  |{:^ #12x}|\n", {420} );
    cout << formatMessage("{{:^ #12X}}     -  |{:^ #12X}|\n", {420} );
    cout << formatMessage("{{:^ !#12x}}    -  |{:^ !#12x}|\n", {420} );
    cout << formatMessage("{{:^ !#12X}}    -  |{:^ !#12X}|\n", {420} );
    cout << formatMessage("{{:*^12}}       -  |{:*^12}|\n", {420} );
    cout << formatMessage("{{:*^12b}}      -  |{:*^12b}|\n", {420} );
    cout << formatMessage("{{:*^12x}}      -  |{:*^12x}|\n", {420} );
    cout << formatMessage("{{:*^12X}}      -  |{:*^12X}|\n", {420} );
    cout << formatMessage("{{:*^12%}}      -  |{:*^12%}|\n", {420} );
    cout << formatMessage("{{:*^#12x}}     -  |{:*^#12x}|\n", {420} );
    cout << formatMessage("{{:*^#12X}}     -  |{:*^#12X}|\n", {420} );
    cout << formatMessage("{{:*^#12h}}     -  |{:*^#12h}|\n", {420} );
    cout << formatMessage("{{:*^!#12x}}    -  |{:*^!#12x}|\n", {420} );
    cout << formatMessage("{{:*^!#12X}}    -  |{:*^!#12X}|\n", {420} );
    cout << formatMessage("{{:*^!#12h}}    -  |{:*^!#12h}|\n", {420} );
    cout << formatMessage("{{:*^+12}}      -  |{:*^+12}|\n", {420} );
    cout << formatMessage("{{:*^+12b}}     -  |{:*^+12b}|\n", {420} );
    cout << formatMessage("{{:*^+12x}}     -  |{:*^+12x}|\n", {420} );
    cout << formatMessage("{{:*^+12X}}     -  |{:*^+12X}|\n", {420} );
    cout << formatMessage("{{:*^+12%}}     -  |{:*^+12%}|\n", {420} );
    cout << formatMessage("{{:*^+#12x}}    -  |{:*^+#12x}|\n", {420} );
    cout << formatMessage("{{:*^+#12X}}    -  |{:*^+#12X}|\n", {420} );
    cout << formatMessage("{{:*^+#12h}}    -  |{:*^+#12h}|\n", {420} );
    cout << formatMessage("{{:*^+!#12x}}   -  |{:*^+!#12x}|\n", {420} );
    cout << formatMessage("{{:*^+!#12X}}   -  |{:*^+!#12X}|\n", {420} );
    cout << formatMessage("{{:*^+!#12h}}   -  |{:*^+!#12h}|\n", {420} );
    cout << formatMessage("{{:*^ 12}}      -  |{:*^ 12}|\n", {420} );
    cout << formatMessage("{{:*^ 12b}}     -  |{:*^ 12b}|\n", {420} );
    cout << formatMessage("{{:*^ 12x}}     -  |{:*^ 12x}|\n", {420} );
    cout << formatMessage("{{:*^ 12X}}     -  |{:*^ 12X}|\n", {420} );
    cout << formatMessage("{{:*^ 12%}}     -  |{:*^ 12%}|\n", {420} );
    cout << formatMessage("{{:*^ #12x}}    -  |{:*^ #12x}|\n", {420} );
    cout << formatMessage("{{:*^ #12X}}    -  |{:*^ #12X}|\n", {420} );
    cout << formatMessage("{{:*^ #12h}}    -  |{:*^ #12h}|\n", {420} );
    cout << formatMessage("{{:*^ !#12x}}   -  |{:*^ !#12x}|\n", {420} );
    cout << formatMessage("{{:*^ !#12X}}   -  |{:*^ !#12X}|\n", {420} );
    cout << formatMessage("{{:*^ !#12h}}   -  |{:*^ !#12h}|\n", {420} );

}


